spring:
  datasource:
    url: jdbc:mysql://localhost/chinasunshine?characterEncoding=utf-8
    username: root
    password: 123456
    connection-test-query: select 1
    max-idle: 50
    min-idle: 5
    max-wait: 10000
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    time-between-eviction-runs-millis: 18800
    xa:
      properties:
        pinGlobalTxToPhysicalConnection: true

  jta:
    bitronix:
      datasource:
        max-pool-size: 50
        min-pool-size: 5
        test-query: select 1

  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
